from typing import Final


KEY_SRC_EXCEL                               : Final[str] = "DB_SRC_EXCEL"                           # Excel ファイル名（必要なら変更）
KEY_DB_NAME                                 : Final[str] = "DB_NAME"                                # 作成される SQLite ファイル

KEY_TBL_CAT_TYPE                            : Final[str] = "TBL_CAT_TYPE"                           # 基準類テーブル
KEY_ITM_CAT_TYPE_PKEY                       : Final[str] = "ITM_CAT_TYPE_PKEY"                      # キー大分類キー
KEY_ITM_CAT_TYPE_TITLE_JP                   : Final[str] = "ITM_CAT_TYPE_TITLE_JP"                  # 日本語名称
KEY_ITM_CAT_TYPE_TITLE_EN                   : Final[str] = "ITM_CAT_TYPE_TITLE_EN"                  # 英語コード
KEY_ITM_CAT_TYPE_PATH                       : Final[str] = "ITM_CAT_TYPE_PATH"                      # 保存先フォルダのパス
KEY_TBL_CAT_MAJOR                           : Final[str] = "TBL_CAT_MAJOR"                          # 基準大分類テーブル
KEY_ITM_CAT_MAJOR_PKEY                      : Final[str] = "ITM_CAT_MAJOR_PKEY"                     # 中分類キー
KEY_ITM_CAT_MAJOR_TITLE_JP                  : Final[str] = "ITM_CAT_MAJOR_TITLE_JP"                 # 日本語名称
KEY_ITM_CAT_MAJOR_TITLE_EN                  : Final[str] = "ITM_CAT_MAJOR_TITLE_EN"                 # 英語名称
KEY_ITM_CAT_MAJOR_FKEY_CAT_TYPE             : Final[str] = "ITM_CAT_MAJOR_FKEY_CAT_TYPE"            # 対応する大分類key_cat_type
KEY_ITM_CAT_MAJOR_PATH                      : Final[str] = "ITM_CAT_MAJOR_PATH"                     # 保存先フォルダのパス
KEY_TBL_CAT_SUB                             : Final[str] = "TBL_CAT_SUB"                            # 基準小分類テーブル
KEY_ITM_CAT_SUB_PKEY                        : Final[str] = "ITM_CAT_SUB_PKEY"                       # 小分類キー
KEY_ITM_CAT_SUB_TITLE_JP                    : Final[str] = "ITM_CAT_SUB_TITLE_JP"                   # 日本語名称
KEY_ITM_CAT_SUB_TITLE_EN                    : Final[str] = "ITM_CAT_SUB_TITLE_EN"                   # 英語名称
KEY_ITM_CAT_SUB_FKEY_CAT_MAJOR              : Final[str] = "ITM_CAT_SUB_FKEY_CAT_MAJOR"             # 対応する中分類key_cat_major
KEY_ITM_CAT_SUB_PATH                        : Final[str] = "ITM_CAT_SUB_PATH"                       # 保存先フォルダのパス
KEY_TBL_CAT_STATE                           : Final[str] = "TBL_CAT_STATE"                          # 基準小分類テーブル
KEY_ITM_CAT_STATE_PKEY                      : Final[str] = "ITM_CAT_STATE_PKEY"                     # 状態ID（0:作成中 1:制定版 2:廃止）
KEY_ITM_CAT_STATE_TITLE_JP                  : Final[str] = "ITM_CAT_STATE_TITLE_JP"                 # 日本語名称
KEY_ITM_CAT_STATE_TITLE_EN                  : Final[str] = "ITM_CAT_STATE_TITLE_EN"                 # 英語名称
KEY_TBL_RULES                               : Final[str] = "TBL_RULES"                              # 基準類テーブル
KEY_ITM_RULES_PKEY                          : Final[str] = "ITM_RULES_PKEY"                         # ルール通し番号
KEY_ITM_RULES_ID_RULE                       : Final[str] = "ITM_RULES_ID_RULE"                      # 文書ID
KEY_ITM_RULES_NAME_RULE                     : Final[str] = "ITM_RULES_NAME_RULE"                    # 文書名
KEY_ITM_RULES_FKEY_CAT_SUB                  : Final[str] = "ITM_RULES_FKEY_CAT_SUB"                 # 小分類キー
KEY_ITM_RULES_LINK                          : Final[str] = "ITM_RULES_LINK"                         # 元文書へのURL
KEY_ITM_RULES_FKEY_CAT_STATE                : Final[str] = "ITM_RULES_FKEY_CAT_STATE"               # 状態ID
KEY_ITM_RULES_CREATED_DATE                  : Final[str] = "ITM_RULES_CREATED_DATE"                 # 制定日など
KEY_ITM_RULES_UPDATE_DATE                   : Final[str] = "ITM_RULES_UPDATE_DATE"                  # 改訂日など
KEY_TBL_CAT_REQUEST                         : Final[str] = "TBL_CAT_REQUEST"                        # 設計領域テーブル
KEY_ITM_CAT_REQUEST_PKEY                    : Final[str] = "ITM_CAT_REQUEST_PKEY"                   # 設計領域ID
KEY_ITM_CAT_REQUEST_TITLE_JP                : Final[str] = "ITM_CAT_REQUEST_TITLE_JP"               # 日本語名称
KEY_ITM_CAT_REQUEST_TITLE_EN                : Final[str] = "ITM_CAT_REQUEST_TITLE_EN"               # 英語名称
KEY_ITM_CAT_REQUEST_KEY_CAT_REQ_TYPE        : Final[str] = "ITM_CAT_REQUEST_KEY_CAT_REQ_TYPE"       # 要件種類ID
KEY_ITM_CAT_REQUEST_REQ_TYPE                : Final[str] = "ITM_CAT_REQUEST_REQ_TYPE"               # 要件種類
KEY_TBL_CAT_PHASE                           : Final[str] = "TBL_CAT_PHASE"                          # 設計領域テーブル
KEY_ITM_CAT_PHASE_PKEY                      : Final[str] = "ITM_CAT_PHASE_PKEY"                     # 設計領域ID
KEY_ITM_CAT_PHASE_TITLE_JP                  : Final[str] = "ITM_CAT_PHASE_TITLE_JP"                 # 日本語名称
KEY_ITM_CAT_PHASE_TITLE_EN                  : Final[str] = "ITM_CAT_PHASE_TITLE_EN"                 # 英語名称
KEY_TBL_SCP_SALES_REGION                    : Final[str] = "TBL_SCP_SALES_REGION"                   # 要件類テーブル
KEY_ITM_SCP_SALES_REGION_PKEY               : Final[str] = "ITM_SCP_SALES_REGION_PKEY"              # 販売地域ID
KEY_ITM_SCP_SALES_REGION_TITLE_JP           : Final[str] = "ITM_SCP_SALES_REGION_TITLE_JP"          # 日本語名称
KEY_ITM_SCP_SALES_REGION_TITLE_EN           : Final[str] = "ITM_SCP_SALES_REGION_TITLE_EN"          # 英語名称
KEY_ITM_SCP_SALES_REGION_COUNTRY_CODE_2     : Final[str] = "ITM_SCP_SALES_REGION_COUNTRY_CODE_2"    # 国コード２桁 ISO 3166-1 alpha-2
KEY_ITM_SCP_SALES_REGION_COUNTRY_CODE_3     : Final[str] = "ITM_SCP_SALES_REGION_COUNTRY_CODE_3"    # 国コード３桁 ISO 3166-1 alpha-3
KEY_TBL_SCP_PRODUCT_GENRE                   : Final[str] = "TBL_SCP_PRODUCT_GENRE"                  # 販売地域テーブル
KEY_ITM_SCP_PRODUCT_GENRE_PKEY              : Final[str] = "ITM_SCP_PRODUCT_GENRE_PKEY"             # 製品ジャンルID
KEY_ITM_SCP_PRODUCT_GENRE_TITLE_JP          : Final[str] = "ITM_SCP_PRODUCT_GENRE_TITLE_JP"         # 日本語名称
KEY_ITM_SCP_PRODUCT_GENRE_TITLE_EN          : Final[str] = "ITM_SCP_PRODUCT_GENRE_TITLE_EN"         # 英語名称
KEY_ITM_SCP_PRODUCT_GENRE_HS_CODE           : Final[str] = "ITM_SCP_PRODUCT_GENRE_HS_CODE"          # HSコード
KEY_TBL_SCP_SERVICE_GENRE                   : Final[str] = "TBL_SCP_SERVICE_GENRE"                  # 販売地域テーブル
KEY_ITM_SCP_SERVICE_GENRE_PKEY              : Final[str] = "ITM_SCP_SERVICE_GENRE_PKEY"             # 製品ジャンルID
KEY_ITM_SCP_SERVICE_GENRE_TITLE_JP          : Final[str] = "ITM_SCP_SERVICE_GENRE_TITLE_JP"         # 日本語名称
KEY_ITM_SCP_SERVICE_GENRE_TITLE_EN          : Final[str] = "ITM_SCP_SERVICE_GENRE_TITLE_EN"         # 英語名称
KEY_TBL_SCP_EQUIPMENT                       : Final[str] = "TBL_SCP_EQUIPMENT"                      # 装備テーブル
KEY_ITM_SCP_EQUIPMENT_PKEY                  : Final[str] = "ITM_SCP_EQUIPMENT_PKEY"                 # 装備ID
KEY_ITM_SCP_EQUIPMENT_TITLE_JP              : Final[str] = "ITM_SCP_EQUIPMENT_TITLE_JP"             # 日本語名称
KEY_ITM_SCP_EQUIPMENT_TITLE_EN              : Final[str] = "ITM_SCP_EQUIPMENT_TITLE_EN"             # 英語名称
KEY_TBL_SCP_PII                             : Final[str] = "TBL_SCP_PII"                            # 装備テーブル
KEY_ITM_SCP_PII_PKEY                        : Final[str] = "ITM_SCP_PII_PKEY"                       # 装備ID
KEY_ITM_SCP_PII_TITLE_JP                    : Final[str] = "ITM_SCP_PII_TITLE_JP"                   # 日本語名称
KEY_ITM_SCP_PII_TITLE_EN                    : Final[str] = "ITM_SCP_PII_TITLE_EN"                   # 英語名称
KEY_TBL_SCP_DESIGN_DOMAIN                   : Final[str] = "TBL_SCP_DESIGN_DOMAIN"                  # 設計領域テーブル
KEY_ITM_SCP_DESIGN_DOMAIN_PKEY              : Final[str] = "ITM_SCP_DESIGN_DOMAIN_PKEY"             # 設計領域ID
KEY_ITM_SCP_DESIGN_DOMAIN_TITLE_JP          : Final[str] = "ITM_SCP_DESIGN_DOMAIN_TITLE_JP"         # 日本語名称
KEY_ITM_SCP_DESIGN_DOMAIN_TITLE_EN          : Final[str] = "ITM_SCP_DESIGN_DOMAIN_TITLE_EN"         # 英語名称
KEY_TBL_REQUEST                             : Final[str] = "TBL_REQUEST"                            # 要件類テーブル
KEY_ITM_REQUEST_PKEY                        : Final[str] = "ITM_REQUEST_PKEY"                       # 要件キー
KEY_ITM_REQUEST_KEY_RULE                    : Final[str] = "ITM_REQUEST_KEY_RULE"                   # 基準キー
KEY_ITM_REQUEST_ID_CAP                      : Final[str] = "ITM_REQUEST_ID_CAP"                     # 章名称
KEY_ITM_REQUEST_FTITLE_CAPTER               : Final[str] = "ITM_REQUEST_FTITLE_CAPTER"              # 節名称
KEY_ITM_REQUEST_TITLE_SECTION               : Final[str] = "ITM_REQUEST_TITLE_SECTION"              # 本文(上)
KEY_ITM_REQUEST_FTOP_BODY                   : Final[str] = "ITM_REQUEST_FTOP_BODY"                  # 本文(下)
KEY_ITM_REQUEST_LOW_BODY                    : Final[str] = "ITM_REQUEST_LOW_BODY"                   # 表(上)
KEY_ITM_REQUEST_TOP_TBL                     : Final[str] = "ITM_REQUEST_TOP_TBL"                    # 図(上)
KEY_ITM_REQUEST_TOP_FIG                     : Final[str] = "ITM_REQUEST_TOP_FIG"                    # 表(下)
KEY_ITM_REQUEST_LOW_TBL                     : Final[str] = "ITM_REQUEST_LOW_TBL"                    # 図(下)
KEY_ITM_REQUEST_LOW_FIG                     : Final[str] = "ITM_REQUEST_LOW_FIG"                    # 参照
KEY_ITM_REQUEST_LEAD_TIME                   : Final[str] = "ITM_REQUEST_LEAD_TIME"                  # リードタイム
KEY_ITM_REQUEST_REFERENCE                   : Final[str] = "ITM_REQUEST_REFERENCE"                  # 参照
KEY_ITM_REQUEST_CREATED_DATE                : Final[str] = "ITM_REQUEST_CREATED_DATE"               # 制定日など
KEY_ITM_REQUEST_FUPDATE_DATE                : Final[str] = "ITM_REQUEST_FUPDATE_DATE"               # 改訂日など
KEY_ITM_REQUEST_FKEY_CAT_REQUEST            : Final[str] = "ITM_REQUEST_FKEY_CAT_REQUEST"           # 要求カテゴリID
KEY_ITM_REQUEST_FKEY_CAT_PHASE              : Final[str] = "ITM_REQUEST_FKEY_CAT_PHASE"             # 対応フェーズID
KEY_ITM_REQUEST_FSCOPE_PRODUCT_GENRE        : Final[str] = "ITM_REQUEST_FSCOPE_PRODUCT_GENRE"       # 製品ジャンル(複数指定可 中間テーブル初回生成用)
KEY_ITM_REQUEST_FSCOPE_SERVICE_GENRE        : Final[str] = "ITM_REQUEST_FSCOPE_SERVICE_GENRE"       # サービスジャンル(複数指定可 中間テーブル初回生成用)
KEY_ITM_REQUEST_FSCOPE_EQUIPMENT            : Final[str] = "ITM_REQUEST_FSCOPE_EQUIPMENT"           # 装備(複数指定可 中間テーブル初回生成用)
KEY_ITM_REQUEST_FSCOPE_PII                  : Final[str] = "ITM_REQUEST_FSCOPE_PII"                 # 個人情報(複数指定可 中間テーブル初回生成用)
KEY_ITM_REQUEST_FSCOPE_DESIGN_DOMAIN        : Final[str] = "ITM_REQUEST_FSCOPE_DESIGN_DOMAIN"       # 設計領域(複数指定可 中間テーブル初回生成用)
KEY_ITM_REQUEST_UNIQUE_SEARCH               : Final[str] = "ITM_REQUEST_UNIQUE_SEARCH"              # 固有条件(複数指定可 中間テーブル初回生成用)
